
ALTER TABLE USERS RENAME COLUMN DELETED TO IS_INVALID;
ALTER TABLE BULLETIN_BOARD RENAME COLUMN DELETED TO IS_INVALID;
ALTER TABLE CLIENTS RENAME COLUMN DELETED TO IS_INVALID;
ALTER TABLE CONTRACTS RENAME COLUMN DELETED TO IS_INVALID;
ALTER TABLE CONTRACTS_TRAN RENAME COLUMN DELETED TO IS_INVALID;
ALTER TABLE PROJECTS RENAME COLUMN DELETED TO IS_INVALID;
ALTER TABLE STAFFS RENAME COLUMN DELETED TO IS_INVALID;
ALTER TABLE BILL_ADDRESSES RENAME COLUMN DELETED TO IS_INVALID;

comment on table USERS is 'ユーザーマスタ';
comment on column USERS.USER_ID is 'ユーザID';
comment on column USERS.PASSWORD is 'パスワード';
comment on column USERS.USER_NAME is 'ユーザ名';
comment on column USERS.ROLE_NAME is 'ロール名';
comment on column USERS.LOGIN_FAILURE_COUNT is 'ログイン失敗回数';
comment on column USERS.LOGIN_DENIED_AT is 'ログイン拒否日時';
comment on column USERS.IS_INVALID is '無効フラグ';
comment on column USERS.UPDATER_ID is '更新者';
comment on column USERS.UPDATED_AT is '更新年月日';
comment on column USERS.CREATER_ID is '登録者';
comment on column USERS.CREATED_AT is '登録年月日';

comment on table STAFFS is 'スタッフマスタ';
comment on column STAFFS.STAFF_NO is 'スタッフNo';
comment on column STAFFS.STAFF_TYPE is 'スタッフ種別';
comment on column STAFFS.STAFF_NAME is '氏名';
comment on column STAFFS.STAFF_NAME_KANA is '氏名（かな）';
comment on column STAFFS.BIRTH_DATE is '生年月日';
comment on column STAFFS.JOINED_DATE is '入社年月日';
comment on column STAFFS.IS_INVALID is '無効フラグ';
comment on column STAFFS.UPDATER_ID is '更新者';
comment on column STAFFS.UPDATED_AT is '更新年月日';
comment on column STAFFS.CREATER_ID is '登録者';
comment on column STAFFS.CREATED_AT is '登録年月日';

comment on table CLIENTS is '取引先マスタ';
comment on column CLIENTS.CLIENT_ID is '取引先ID';
comment on column CLIENTS.CLIENT_NAME is '取引先名';
comment on column CLIENTS.SALES_STAFF_NO is '担当営業No';
comment on column CLIENTS.IS_INVALID is '無効フラグ';
comment on column CLIENTS.UPDATER_ID is '更新者';
comment on column CLIENTS.UPDATED_AT is '更新年月日';
comment on column CLIENTS.CREATER_ID is '登録者';
comment on column CLIENTS.CREATED_AT is '登録年月日';

comment on table BULLETIN_BOARD is 'お知らせ';
comment on column BULLETIN_BOARD.BULLETIN_BOARD_ID is 'お知らせID';
comment on column BULLETIN_BOARD.CONTENTS is '内容';
comment on column BULLETIN_BOARD.IS_INVALID is '無効フラグ';
comment on column BULLETIN_BOARD.CREATER_ID is '登録者';
comment on column BULLETIN_BOARD.CREATED_AT is '登録年月日';

comment on table PROJECTS is '案件マスタ';
comment on column PROJECTS.PROJECT_ID is '案件ID';
comment on column PROJECTS.PROJECT_NAME is '案件名';
comment on column PROJECTS.CLIENT_ID is '取引先ID';
comment on column PROJECTS.BILL_ADDRESS_ID is '請求先ID';
comment on column PROJECTS.SKILLS is '主要技術';
comment on column PROJECTS.OVERVIEWS is '業務内容';
comment on column PROJECTS.REMARKS is '備考';
comment on column PROJECTS.IS_INVALID is '無効フラグ';
comment on column PROJECTS.UPDATER_ID is '更新者';
comment on column PROJECTS.UPDATED_AT is '更新年月日';
comment on column PROJECTS.CREATER_ID is '登録者';
comment on column PROJECTS.CREATED_AT is '登録年月日';

comment on table CONTRACTS is '契約ヘッダ情報';
comment on column CONTRACTS.CONTRACT_ID is '契約ID';
comment on column CONTRACTS.PROJECT_ID is '案件ID';
comment on column CONTRACTS.STAFF_NO is 'スタッフNo';
comment on column CONTRACTS.IS_INVALID is '無効フラグ';
comment on column CONTRACTS.UPDATER_ID is '更新者';
comment on column CONTRACTS.UPDATED_AT is '更新年月日';
comment on column CONTRACTS.CREATER_ID is '登録者';
comment on column CONTRACTS.CREATED_AT is '登録年月日';

comment on table CONTRACTS_TRAN is '契約トラン情報';
comment on column CONTRACTS_TRAN.CONTRACT_ID is '契約ID';
comment on column CONTRACTS_TRAN.SUB_NO is '契約枝番';
comment on column CONTRACTS_TRAN.CONTRACT_PERIOD_FROM is '契約期間From';
comment on column CONTRACTS_TRAN.CONTRACT_PERIOD_TO is '契約期間To';
comment on column CONTRACTS_TRAN.CONTRACT_TYPE is '契約種別';
comment on column CONTRACTS_TRAN.UNIT_PRICE is '単価';
comment on column CONTRACTS_TRAN.WORKING_HOURS_MIN is '稼働時間(下限)';
comment on column CONTRACTS_TRAN.WORKING_HOURS_MAX is '稼働時間(上限)';
comment on column CONTRACTS_TRAN.OVERTIME_PREMIUM_PRICE is '超過割増分単価';
comment on column CONTRACTS_TRAN.SHORTAGE_DEDUCTIONS_PRICE is '未達控除分単価';
comment on column CONTRACTS_TRAN.REMARKS is '備考';
comment on column CONTRACTS_TRAN.IS_INVALID is '無効フラグ';
comment on column CONTRACTS_TRAN.UPDATER_ID is '更新者';
comment on column CONTRACTS_TRAN.UPDATED_AT is '更新年月日';
comment on column CONTRACTS_TRAN.CREATER_ID is '登録者';
comment on column CONTRACTS_TRAN.CREATED_AT is '登録年月日';

comment on table BILL_ADDRESSES is '請求先マスタ';
comment on column BILL_ADDRESSES.BILL_ADDRESS_ID is '請求先ID';
comment on column BILL_ADDRESSES.CLIENT_ID is '取引先ID';
comment on column BILL_ADDRESSES.SPECIFIED_FORMAT_TYPE is '客先指定';
comment on column BILL_ADDRESSES.SITE is 'サイト';
comment on column BILL_ADDRESSES.BILL_UNIT_TYPE is '請求単位種別';
comment on column BILL_ADDRESSES.BILL_UNIT is '請求単位';
comment on column BILL_ADDRESSES.ZIP_CODE is '郵便番号';
comment on column BILL_ADDRESSES.ADRESS1 is '住所１';
comment on column BILL_ADDRESSES.ADRESS2 is '住所２';
comment on column BILL_ADDRESSES.COMPANY_NAME1 is '会社名１';
comment on column BILL_ADDRESSES.COMPANY_NAME2 is '会社名２';
comment on column BILL_ADDRESSES.COMPANY_NAME3 is '会社名３';
comment on column BILL_ADDRESSES.COMPANY_NAME4 is '会社名４';
comment on column BILL_ADDRESSES.IS_INVALID is '無効フラグ';
comment on column BILL_ADDRESSES.UPDATER_ID is '更新者';
comment on column BILL_ADDRESSES.UPDATED_AT is '更新年月日';
comment on column BILL_ADDRESSES.CREATER_ID is '登録者';
comment on column BILL_ADDRESSES.CREATED_AT is '登録年月日';
