CREATE PROFILE DEV_PROFILE LIMIT
 SESSIONS_PER_USER DEFAULT
 CPU_PER_SESSION DEFAULT
 CPU_PER_CALL DEFAULT
 CONNECT_TIME DEFAULT
 IDLE_TIME DEFAULT
 LOGICAL_READS_PER_SESSION DEFAULT
 LOGICAL_READS_PER_CALL DEFAULT
 COMPOSITE_LIMIT DEFAULT
 PRIVATE_SGA DEFAULT
 FAILED_LOGIN_ATTEMPTS UNLIMITED
 PASSWORD_LIFE_TIME UNLIMITED
 PASSWORD_LOCK_TIME UNLIMITED
 PASSWORD_GRACE_TIME UNLIMITED;

Create User IMUSER Identified By "impass" PROFILE DEV_PROFILE;
Grant CONNECT              To IMUSER With Admin Option;
Grant UNLIMITED TABLESPACE To IMUSER With Admin Option;
Alter User IMUSER Default Role All;

Grant CREATE TABLE TO IMUSER With Admin Option;
Grant CREATE SEQUENCE TO IMUSER With Admin Option;
Grant CREATE VIEW TO IMUSER With Admin Option;
